services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: backend-ms-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: andina_trading
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - andina_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # FastAPI Application
  app:
    build: .
    container_name: backend-ms-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - docker.env
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: andina_trading
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - andina_network
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data:

networks:
  andina_network:
    driver: bridge